dubbo:
  application:
    name: shop_service
  registry:
#    address: zookeeper://192.168.154.130:2181
     address: zookeeper://112.74.43.238:2181
     timeout: 5000
server:
  port: 8888
spring:
  datasource:
    username: root
    password: root
#    url: jdbc:mysql:///shop
    url: jdbc:mysql://112.74.43.238:3306/shop
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mchange.v2.c3p0.ComboPooledDataSource
mybatis:
  type-aliases-package: com.xu.entity
  mapper-locations: classpath*:com/xu/dao/mapper/*.xml
